export type CatalogIngredient = {
  id: string;
  name: string;
  icon: string;
  cat: string;
};

export const CATALOG_INGREDIENTS: CatalogIngredient[] = [
  { id: 'chicken', name: 'Chicken', icon: '🍗', cat: 'proteins' },
  { id: 'beef', name: 'Beef', icon: '🥩', cat: 'proteins' },
  { id: 'fish', name: 'Fish', icon: '🐟', cat: 'proteins' },
  { id: 'shrimp', name: 'Shrimp', icon: '🦐', cat: 'proteins' },
  { id: 'egg', name: 'Egg', icon: '🥚', cat: 'proteins' },
  { id: 'tofu', name: 'Tofu', icon: '🥡', cat: 'proteins' },
  { id: 'turkey', name: 'Turkey', icon: '🦃', cat: 'proteins' },
  { id: 'lamb', name: 'Lamb', icon: '🍖', cat: 'proteins' },
  { id: 'tomato', name: 'Tomato', icon: '🍅', cat: 'vegetables' },
  { id: 'onion', name: 'Onion', icon: '🧅', cat: 'vegetables' },
  { id: 'garlic', name: 'Garlic', icon: '🧄', cat: 'vegetables' },
  { id: 'potato', name: 'Potato', icon: '🥔', cat: 'vegetables' },
  { id: 'carrot', name: 'Carrot', icon: '🥕', cat: 'vegetables' },
  { id: 'pepper', name: 'Pepper', icon: '🟢', cat: 'vegetables' },
  { id: 'spinach', name: 'Spinach', icon: '🥬', cat: 'vegetables' },
  { id: 'mushroom', name: 'Mushroom', icon: '🍄', cat: 'vegetables' },
  { id: 'corn', name: 'Corn', icon: '🌽', cat: 'vegetables' },
  { id: 'broccoli', name: 'Broccoli', icon: '🥦', cat: 'vegetables' },
  { id: 'zucchini', name: 'Zucchini', icon: '🥒', cat: 'vegetables' },
  { id: 'cucumber', name: 'Cucumber', icon: '🥒', cat: 'vegetables' },
  { id: 'lettuce', name: 'Lettuce', icon: '🥗', cat: 'vegetables' },
  { id: 'celery', name: 'Celery', icon: '🌿', cat: 'vegetables' },
  { id: 'peas', name: 'Peas', icon: '🌱', cat: 'vegetables' },
  { id: 'cabbage', name: 'Cabbage', icon: '🥬', cat: 'vegetables' },
  { id: 'avocado', name: 'Avocado', icon: '🥑', cat: 'vegetables' },
  { id: 'cauliflower', name: 'Cauliflower', icon: '🥦', cat: 'vegetables' },
  { id: 'cheese', name: 'Cheese', icon: '🧀', cat: 'dairy' },
  { id: 'milk', name: 'Milk', icon: '🥛', cat: 'dairy' },
  { id: 'butter', name: 'Butter', icon: '🧈', cat: 'dairy' },
  { id: 'cream', name: 'Cream', icon: '🍦', cat: 'dairy' },
  { id: 'yogurt', name: 'Yogurt', icon: '🥣', cat: 'dairy' },
  { id: 'parmesan', name: 'Parmesan', icon: '🧀', cat: 'dairy' },
  { id: 'mozzarella', name: 'Mozzarella', icon: '🧀', cat: 'dairy' },
  { id: 'feta', name: 'Feta', icon: '🧀', cat: 'dairy' },
  { id: 'bread', name: 'Bread', icon: '🍞', cat: 'grains' },
  { id: 'rice', name: 'Rice', icon: '🍚', cat: 'grains' },
  { id: 'pasta', name: 'Pasta', icon: '🍝', cat: 'grains' },
  { id: 'flour', name: 'Flour', icon: '🌾', cat: 'grains' },
  { id: 'noodles', name: 'Noodles', icon: '🍜', cat: 'grains' },
  { id: 'tortilla', name: 'Tortilla', icon: '🌮', cat: 'grains' },
  { id: 'quinoa', name: 'Quinoa', icon: '🌾', cat: 'grains' },
  { id: 'salt', name: 'Salt', icon: '🧂', cat: 'spices' },
  { id: 'chili', name: 'Chili', icon: '🌶️', cat: 'spices' },
  { id: 'cumin', name: 'Cumin', icon: '⚫', cat: 'spices' },
  { id: 'basil', name: 'Basil', icon: '🍃', cat: 'spices' },
  { id: 'oregano', name: 'Oregano', icon: '🌿', cat: 'spices' },
  { id: 'paprika', name: 'Paprika', icon: '🔴', cat: 'spices' },
  { id: 'turmeric', name: 'Turmeric', icon: '💛', cat: 'spices' },
  { id: 'ginger', name: 'Ginger', icon: '🟠', cat: 'spices' },
  { id: 'olive_oil', name: 'Olive Oil', icon: '🥄', cat: 'pantry' },
  { id: 'soy_sauce', name: 'Soy Sauce', icon: '🥫', cat: 'pantry' },
  { id: 'honey', name: 'Honey', icon: '🍯', cat: 'pantry' },
  { id: 'beans', name: 'Beans', icon: '🥫', cat: 'pantry' },
  { id: 'chickpeas', name: 'Chickpeas', icon: '🟡', cat: 'pantry' },
  { id: 'lentils', name: 'Lentils', icon: '🟠', cat: 'pantry' },
  { id: 'lemon', name: 'Lemon', icon: '🍋', cat: 'pantry' },
  { id: 'tomato_sauce', name: 'Tomato Sauce', icon: '🥫', cat: 'pantry' },
  { id: 'broth', name: 'Broth', icon: '🍲', cat: 'pantry' },
];

export const INGREDIENT_CATEGORIES = [
  { id: 'proteins', label: 'Proteins' },
  { id: 'vegetables', label: 'Vegetables' },
  { id: 'dairy', label: 'Dairy' },
  { id: 'grains', label: 'Grains' },
  { id: 'spices', label: 'Spices' },
  { id: 'pantry', label: 'Pantry' },
] as const;
